#pragma once

// CPU particles and effects in both eyes of a Route S tick (stereo_seq/fx_sync.hpp,
// docs/rig-findings/stereo-fx-lag.md; Steam build 25216728). Off by default since 0.1.35;
// ETERNALVR_STEREO_FX_SYNC=1 turns it on, =count only counts, unset patches nothing.
//
// The world's per-render prepare (0x18E78D0) advances the particle vertex ring (call 0x1A0F5D0 at RVA
// 0x18E791C) and resets the particle light pool's count (call 0x1953D80 at RVA 0x18E7ABD); the particle
// update (0x1955150) and the effect update (0x19511E0) then bind the vertices the render before generated,
// the particles' lights with them, and generate new ones (call 0x1953D90 at RVA 0x195526F; from RVA
// 0x195166E). In eye R's render the hooks keep the ring where eye L left it (its previous slot's pointer
// reopened, as the advance would have) and the pool's count with it, and skip the generation of every model
// eye L generated in the tick, so eye R draws what eye L bound and shows eye L's particle lights. A model eye
// L did not generate runs the engine's code. A particle system with GPU particles (fx_gpu_stages.hpp) has
// its GPU stages bound by eye R and is generated by eye R as the engine does (ETERNALVR_STEREO_FX_SYNC_GPU=0
// reuses it like the rest, as 0.1.34 did).
//
// Located by signature and cross-checked; anything missing installs nothing and logs why (the GPU stages'
// checks too, unless =count or ETERNALVR_STEREO_FX_SYNC_GPU=0). All four hooks act or none does; a read-only
// hook on the GPU particle step adds per-eye counts to the 10 s line when it checks out.

namespace evr::vkcore {

// Locates and installs the hooks once per process; later calls return the first result.
bool installFxSyncHooks();

} // namespace evr::vkcore
